export { default as Login } from './login'
/* no login */
export { default as Register } from './register'
export { default as Home } from './home'
export { default as Search } from './search'
export { default as Subject } from './subject'
export { default as ForgotPassword } from './forgotPassword'
export { default as NewPassword } from './newPassword'
export { default as NotFound } from './notFound'
export { default as ListPost } from './listPost'
/* login */
export { default as Detail } from './detail'
export { default as Info } from './info'
export { default as CourseRegister } from './courseRegister'
export { default as ListReview } from './listReview'
export { default as ListComment } from './listComment'
export { default as FormCourse } from './formCourse'
export { default as ManagerCourse } from './managerCourse'
export { default as ContentCourse } from './contentCourse'
export { default as ManagerQuestion } from './managerQuestion'
export { default as ManagerLesson } from './managerLesson'
export { default as ManagerExam } from './managerExam'
export { default as DetailExam } from './detailExam'
export { default as FormExam } from './formExam'
export { default as ManagerOption } from './managerOption'
export { default as FormPost } from './formPost'
/* admin */
export { default as Admin } from './admin'
export { default as LoginAdmin } from './loginAdmin'
export { default as CreateAccount } from './createAccount'
export { default as ListAccount } from './listAccount'
export { default as ManagerSubject } from './managerSubject'
export { default as ManagerRole } from './managerRole'
export { default as ListStatus } from './listStatus'
export { default as ManagerCategory } from './managerCategory'
export { default as ListType } from './listType'
export { default as ManagerPost } from './managerPost'