export { default as Login } from './login'
/* no login */
export { default as Register } from './register'
export { default as Home } from './home'
export { default as ForgotPassword } from './forgotPassword'
export { default as NewPassword } from './newPassword'
export { default as NotFound } from './notFound'
export { default as DetailDocument } from './detailDocument'
export { default as DetailPost } from './detailPost'
export { default as DetailStore } from './detailStore'
export { default as Search } from './search'
export { default as ListStore } from './listStore'
/* login */
export { default as ListHistory } from './listHistory'
export { default as BuyDocument } from './buyDocument'
export { default as Point } from './point'
export { default as Info } from './info'
export { default as FormPost } from './formPost'
export { default as ListPost } from './listPost'
export { default as ListBuy } from './listBuy'
/* admin */
export { default as Admin } from './admin'
export { default as ManagerPoint } from './managerPoint'
export { default as ManagerDocument } from './managerDocument'
export { default as CreateAccount } from './createAccount'
export { default as ListAccount } from './listAccount'
export { default as ManagerStore } from './managerStore'
export { default as ListStatus } from './listStatus'
export { default as ManagerFormat } from './managerFormat'
export { default as ManagerPost } from './managerPost'
export { default as Revenue } from './revenue'