export { default as Login } from './login'
/* no login */
export { default as Register } from './register'
export { default as Home } from './home'
export { default as Search } from './search'
export { default as Field } from './field'
/* login */
export { default as Detail } from './detail'
export { default as Info } from './info'
export { default as CourseRegister } from './courseRegister'
export { default as ListReview } from './listReview'
export { default as ListComment } from './listComment'
export { default as FormCourse } from './formCourse'
export { default as ManagerCourse } from './managerCourse'
export { default as ContentCourse } from './contentCourse'
export { default as ManagerQuestion } from './managerQuestion'
export { default as QuestionResource } from './questionResource'
export { default as ManagerLesson } from './managerLesson'
export { default as ManagerExam } from './managerExam'
export { default as DetailExam } from './detailExam'
export { default as FormExam } from './formExam'
/* admin */
export { default as Admin } from './admin'
export { default as CreateAccount } from './createAccount'
export { default as ListAccount } from './listAccount'
export { default as ListCourseAdmin } from './listCourseAdmin'
export { default as ListField } from './listField'